Add date to the log. Add log message for copying to last.sql.gz

diff --git a/bin/cron-job b/bin/cron-job
--- a/bin/cron-job
+++ b/bin/cron-job
@@ -17,14 +17,23 @@ make_backup () {
 
     mysqldump -h $MYSQL_HOST -P $MYSQL_PORT -u $MYSQL_USER -p$MYSQL_PASSWORD --all-databases | gzip -9 -c | aws s3 cp - --region=$REGION s3://$BUCKET/$FILE
 
-    aws s3 cp --region=$REGION s3://$BUCKET/$FILE s3://$BUCKET/last.sql.gz
-
     # exit if last command have problems
     if  [ "$?" == "0" ]; then
-        echo "Backup process complete";
+        echo "`date`: Backup process complete";
     else
-        echo "Error occurred in backup process. Exiting now"
-        kill -9 $PID
+        echo "`date`: Error occurred in backup process."
+        if [ "$KILL_IF_ANY_FAIL" ]; then
+            kill -9 $PID
+        fi
+    fi
+
+    # copies the freshly created backup to last.sql.gz
+    aws s3 cp --region=$REGION s3://$BUCKET/$FILE s3://$BUCKET/last.sql.gz
+
+    if  [ "$?" == "0" ]; then
+        echo "`date`: Copied to last.sql.gz";
+    else
+        echo "`date`: Error occurred at last.sql.gz creation."
     fi
 
 }
